### ISSUE TITLE
It would be great to be able to select the channel/branch 

### ISSUE THREAD

**Issue by pipiche38** [ycahome/pp-manager#16]
As there is now the Github branch available, it might be interesting for the end user to be able to select the channel they want to follow.

We can for instance instead of having a single branche in the plugin config, to have a list of branches (starting with the default one). Then in the pp-manager UI screen when selecting a Plugin to add, we can also ask for the channel to follow.

**Comment by ycahome** [comment]
In order to accomplish that, you need a plugin interface to configure all those parameters.
Currently, python plugin number of parameter variables not allowing such approach.

**Comment by pipiche38** [comment]
You are right. Would you mind to have 2 entries for the same plugin one for beta and one for master branch ?

Envoyé de mon iPhone

**Comment by pipiche38** [comment]
Looks like it is now possible via a Custom Page
https://github.com/stas-demydiuk/domoticz-plugins-manager
