### ISSUE TITLE
New plugin - Sonoff Mini

### ISSUE THREAD

**Issue by bobzomer** [ycahome/pp-manager#32]
I've written a small plugin to integrate with Sonoff Mini DIY mode (see [https://sonoff.tech/product/wifi-diy-smart-switches/sonoff-mini](https://sonoff.tech/product/wifi-diy-smart-switches/sonoff-mini)). Currently it allows only to switch on / switch off the switch (which is what we really want from a smart switch).

Maybe you integrate it in your list? 

Github repo: [https://github.com/bobzomer/sonoff-domoticz-plugin](https://github.com/bobzomer/sonoff-domoticz-plugin)

**Comment by ycahome** [comment]
A "Pull Request" is usually expected but, i 've made an exception this time :-)
"SonOff Mini" plugin added.
